import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/leclerc-fonts.css";

// Providers
import { CartProvider } from "./providers/cart-provider";
import { AddressProvider } from "./providers/address-provider";
import { RestaurantThemeProvider } from "./hooks/use-restaurant-theme";
import { ErrorBoundary } from "./components/error-boundary";

// Load Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// App Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <RestaurantThemeProvider defaultThemePath="/themes/leclerc-theme.json">
            <AddressProvider>
              <CartProvider>{children}</CartProvider>
            </AddressProvider>
          </RestaurantThemeProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
